spring:
  cloud:
    vault:
      app-role:
        app-role-path: approle
        role: appfnd
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      uri: https://kmsdev.hanatour.com:8200